source 'https://rubygems.org'

gem "nyan-cat-formatter"
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-rails'
gem 'capistrano-rvm'
gem 'factory_girl_rails'
# gem 'fuubar'
gem 'nokogiri'
gem 'pry'
gem 'pry-debugger'
gem 'railroady'
gem 'rails-erd'
gem 'rspec-rails'
gem 'simplecov'
# gem 'bcrypt-ruby', '~> 3.0.0'
# gem 'capistrano'
# gem 'jbuilder'
# gem 'ruby-debug19', :require => 'ruby-debug'
# gem 'unicorn'
gem 'active_model_serializers'
gem 'apartment'
gem 'api_pagination_headers'
gem 'colorize'
gem 'dalli'
gem 'devise'
gem 'faker'
gem 'foreigner'
gem 'globalize'
gem 'mysql2'
gem 'pry-remote'
gem 'rails'
gem 'rails-api'
gem 'will_paginate'
gem 'gollum'
gem 'redcarpet'